---
### Packages
- name: Add Ruby repository
  with_items:
    - ppa:brightbox/ruby-ng
  apt_repository: repo={{ item }}

- name: Install Packages
  apt: name={{ item }} state=present update_cache=true
  with_items:
    - build-essential
    - git
    - libxml2-dev
    - libxslt1-dev
    - libssl-dev
    - zlib1g-dev
    - libpq-dev
    - nodejs
    - curl
    - wget
    - ruby2.2
    - ruby2.2-dev
    - ruby-switch
    - nginx

- name: Dont install gem docs, they will slow down gem install
  lineinfile: "dest=/etc/gemrc line='gem: --no-ri --no-rdoc' create=yes"

# Bundler
- name: Check bundler is installed or not
  shell: bundle -v
  register: bundler_present
  ignore_errors: True

- name: Check bundler is installed or not
  shell: foreman -h
  register: foreman_present
  ignore_errors: True

- name: Install bundler if not yet present
  shell: gem install bundler
  when: bundler_present|failed

- name: Install foreman if not yet present
  shell: gem install foreman
  when: foreman_present|failed

# Nginx
- name: copy nginx site file for default/factu.ly
  template: src=default.j2 dest=/etc/nginx/sites-available/default

- name: copy nginx site file for newspaper-app
  template: src=newspaper.j2 dest=/etc/nginx/sites-available/newspaper

- name: Copy nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: install setfacl support
  become: yes
  apt: pkg=acl

- name: Create dir for ssl certs
  file: path=/etc/nginx/ssl state=directory

- name: Copy ssl certificates
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'fullchain.pem', dest: '/etc/nginx/ssl' }
    - { src: 'privkey.pem', dest: '/etc/nginx/ssl' }
