---
- name: Install python packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - python3-pip
    - libjpeg-dev
    - zlib1g-dev
    - libpng12-dev
    - gunicorn
