---
# Effectively lifted from the Ansible documentation on EC2:
# http://docs.ansible.com/ec2_module.html

  - name: Provision and deploy to ec2 instance
    hosts: launched
    become: yes # On EC2 nodes, this is automatically passwordless.
    remote_user: ubuntu # This is the username for all ubuntu images, rather than root, or something weird.
    gather_facts: True  #We need to re-enable this, as we turned it off earlier.
    roles:
      - ruby
      - python
      - postgresql
      - factuly
      - newspaper-api
